import { NextPage } from "next";
import Head from "next/head";

import { FC } from "react";

const Home: NextPage = () => {
  // TODO: dynamic title (Nander | ~/home etc.)

  const Section: FC<{ title: string }> = ({ children, title }) => (
    <section className="p-4 shadow-xl rounded-2xl">
      <h2 className="font-bold text-4xl mb-1">{title}</h2>
      <p className="text-lg">{children}</p>
    </section>
  );

  return (
    <div>
      <Head>
        <title>Nander | ~/</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-12 mt-16 md:mt-32">
        <h1 className="font-bold text-8xl text-center md:text-left">Nander</h1>
        <div className="flex flex-wrap flex-col gap-4 max-w-prose">
          <div>
            <Section title="About me">
              I am a young fullstack web-developer currently practicing UI/UX.
              Living in Germany. Interested in Svelte, Rust and Cryptography.
              You can find me on{" "}
              <a
                href="https://discord.com/users/329630845805789186"
                className="underline decoration-blue decoration-4"
                title="Nander#0001"
              >
                Discord
              </a>
              .
            </Section>
          </div>
          <Section title="Projects">
            Here is a selection of some of my projects I like. You can find all
            my projects on my{" "}
            <a
              href="https://github.com/nanderLP"
              className="underline decoration-blue decoration-4"
              title="@nanderLP"
            >
              GitHub
            </a>
          </Section>
        </div>
      </main>
    </div>
  );
};

export default Home;
