import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { motion } from "framer-motion";

import styles from "../styles/Home.module.css";
import Box from "../components/Box";
import { BoxProps } from "../types/Box";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  // TODO: dynamic title (Nander | ~/home etc.)

  const router = useRouter();

  const animate = router.query.b !== undefined;

  console.log(animate);

  const boxes: BoxProps[] = [
    {
      title: "About",
      color: "blue",
      href: "/about",
    },
    /*{
      title: "Projects",
      color: "green",
      href: "/projects",
    },*/
    {
      title: "Blog",
      color: "red",
      href: "/blog",
    },
  ];

  const container = {
    hidden: { opacity: 1, scale: 0 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        delayChildren: 0.3,
        staggerChildren: 0.2,
      },
    },
  };

  const item = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
    },
  };

  return (
    <div>
      <Head>
        <title>Nander | ~/</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-4 md:mx-16 mt-4 md:mt-32">
        <h1 className="font-bold text-8xl">Nander</h1>

        {/* with grid: className="grid gap-4 grid-cols-2 mt-4" */}
        <motion.div
          className="grid gap-24 grid-rows-2 mt-4"
          variants={container}
          initial={animate ? "visible" : "hidden"}
          animate={animate ? undefined : "visible"}
        >
          {/*<motion.div variants={item} key={i}>            </motion.div>*/}

          {boxes.map((box, i) => (
            <motion.div variants={item} key={i}>
              <Box color={box.color} title={box.title} href={box.href}></Box>
            </motion.div>
          ))}
        </motion.div>
      </main>
    </div>
  );
};

export default Home;
